chore: Cleanup example and improve GitHub CI (WIP)
MindscapeHQ/raygun4flutter pull request #175
Opened 2024-05-17 12:38 UTC by miquelbeltran

## chore: Cleanup example and improve GitHub CI

### Description :memo:
- **Purpose**: Ensure the example builds without problems
- **Approach**: Fix Android build and implement CI jobs for all platforms

**Type of change**

*Delete options that are not relevant.*

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Updates**

:point_right:
:point_right:
:point_right:

### Screenshots :camera:
{Image here of before and after - if applicable}

### Test plan :test_tube:
*Provide guidance for how to QA your proposed changes. This is not only for a test but also useful for a reviewer.*

{A test plan outlining scenarios to test}

### Author to check :eyeglasses:
- [ ] Project and all contained modules builds successfully
- [ ] Self-/dev-tested 
- [ ] Unit/UI/Automation/Integration tests provided where applicable
- [ ] Code is written to standards
- [ ] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:
- [ ] Project and all contained modules builds successfully
- [ ] Change has been dev-/reviewer-tested, where possible
- [ ] Unit/UI/Automation/Integration tests provided where applicable
- [ ] Code is written to standards
- [ ] Appropriate documentation written (code comments, internal docs)

2024-05-20 03:29 UTC, sumitramanga commented on example/ios/Podfile
It says to uncomment this line but the line is already commented 😅

2024-05-20 03:31 UTC, sumitramanga commented on example/test/widget_test.dart
Why did this get deleted?

2024-05-20 03:32 UTC, sumitramanga commented on .github/workflows/main.yml
> +    timeout-minutes: 30
30 minutes is a long time. How long does a build typically last? It should that plus minimal buffer. Unless I am missing something :)

2024-05-20 03:45 UTC, sumitramanga requested changes
Some things to look into. Well done so far!! 💪🏽

2024-05-20 04:41 UTC, miquelbeltran commented on example/ios/Podfile
The comment is probably from the original autogenerated template.

This has to be increased because one of the dependencies has a higher version requirement.

This is in the example project, not the Raygun package, btw.

2024-05-20 04:41 UTC, miquelbeltran commented on example/test/widget_test.dart
It was included by mistake. When generating a Flutter project it creates a template for widgets tests, but because this is the example project, no tests are needed.

2024-05-20 04:43 UTC, miquelbeltran commented on .github/workflows/main.yml
> +    timeout-minutes: 30
You can find the execution times in the checks list:

![image](https://github.com/MindscapeHQ/raygun4flutter/assets/2494376/72fa17a2-4433-4d9d-84e6-dd87c0bde4fd)

I use the 30-minute timeout in other Flutter projects, just in case the native compilers do something wrong.

2024-05-21 01:54 UTC, sumitramanga commented on .github/workflows/main.yml
> +    timeout-minutes: 30
Thank you! I see that it is also recommended by ChatGPT to have a 30 minute window. But our builds take under 10 minutes. We can leave it as is though

2024-05-21 01:54 UTC, sumitramanga approved these changes
LGTM, thank you for spending some time to clarify things with me! 🎸

2024-05-21 05:29 UTC, merged