Add onBeforeSend implementation
MindscapeHQ/raygun4flutter pull request #57
Opened 2022-04-19 15:22 UTC by miquelbeltran

2022-04-19 15:23 UTC, miquelbeltran commented on lib/src/messages/raygun_breadcrumb_message.dart
> +  String? lineNumber;
Class members are no longer final, so users can modify them before sending the payload

2022-04-26 03:20 UTC, TheRealAgentK requested changes

2022-04-26 03:20 UTC, TheRealAgentK commented on example/android/app/src/main/kotlin/com/raygun/raygun4flutter/raygun4flutter_example/MainActivity.kt
> -package com.raygun.raygun4flutter.raygun4flutter_example
Was this file still in there from the early iterations leveraging the native provider?

2022-04-26 03:22 UTC, TheRealAgentK commented
I think this looks good to go from a lib level, it might be nice if there was an example of `onBeforeSend` in the actual example app too.

Should we then release this at a 1.1.5-beta and let some interested parties know about it and get them to try it for their use case?

2022-04-26 08:29 UTC, miquelbeltran commented on example/android/app/src/main/kotlin/com/raygun/raygun4flutter/raygun4flutter_example/MainActivity.kt
> -package com.raygun.raygun4flutter.raygun4flutter_example
Nope, this was part of the example project, nothing to do with the java client.

Since having a "FlutterActivity" in a Flutter project is no longer required, then we don't need this file so it was removed.

2022-04-26 08:29 UTC, miquelbeltran commented
yes, good point, I will add an example

2022-04-26 20:49 UTC, TheRealAgentK approved these changes

2022-04-26 23:47 UTC, merged